module.exports = {
	rep: "Zac Messinger",
	repType: "Customer Success Engineer",
	accounts: [
		{ title: "TMO", value: "T-Mobile Us, Inc." },
		{ title: "WU", value: "Western Union Financial Services, Inc." },
		{ title: "SKIMS", value: "Skims" },
	],
	types: [
		{ title: "Administrative Work & Status Call", value: "Administrative Work & Status Call", recordType: "External" },
		{ title: "Business Review Call", value: "Business Review Call", recordType: "External" },
		{ title: "Call Observation", value: "Call Observation", recordType: "External" },
		{ title: "Consultative Call", value: "Consultative Call", recordType: "External" },
		{ title: "Executive Business Review", value: "Executive Business Review", recordType: "External" },
		{ title: "Insights & Enablement", value: "Guided Insights & Enablement", recordType: "External" },
		{ title: "Question Emails", value: "How To Question Emails", recordType: "External" },
		{ title: "Insights Brief", value: "Insights Brief", recordType: "External" },
		{ title: "Introductory Training", value: "Introductory Training", recordType: "External" },
		{ title: "Kickoff Call", value: "Kickoff call", recordType: "External" },
		{ title: "Monthly Ongoing Enablement", value: "Monthly Ongoing Enablement", recordType: "External" },
		{ title: "Onboarding: Dashboards", value: "Onboarding: Dashboard/reports/alerts creation", recordType: "External" },
		{ title: "Onboarding: Event creation", value: "Onboarding: Events creation", recordType: "External" },
		{ title: "Onboarding: Integration Work", value: "Onboarding: Integration Work", recordType: "External" },
		{ title: "Onboarding: Native Event Creation", value: "Onboarding: Native Event Creation", recordType: "External" },
		{ title: "Onboarding: Native PII Remediation", value: "Onboarding: Native PII Remediation", recordType: "External" },
		{ title: "Onboarding: PII Remediation", value: "Onboarding: PII Remediation", recordType: "External" },
		{ title: "Ongoing: AM", value: "Ongoing: Account Maintenance", recordType: "External" },
		{ title: "Ongoing: Dashboards", value: "Ongoing: Dashboard/reports/alerts creation", recordType: "External" },
		{ title: "Ongoing: Event creation", value: "Ongoing: Events creation", recordType: "External" },
		{ title: "Ongoing: Integration Work", value: "Ongoing: Integration Work", recordType: "External" },
		{ title: "Ongoing: Native Event Creation", value: "Ongoing: Native Event Creation", recordType: "External" },
		{ title: "Ongoing: Native PII Remediation", value: "Ongoing: Native PII Remediation", recordType: "External" },
		{ title: "Ongoing: PII Remediation", value: "Ongoing: PII Remediation", recordType: "External" },
		{ title: "Ongoing: Use Case Based Training", value: "Ongoing: Use Case Based Training", recordType: "External" },
		{ title: "Onsite Visit", value: "Onsite Visit", recordType: "External" },
		{ title: "Proactive Monitoring Insights", value: "Proactive Monitoring Insights", recordType: "External" },
		{ title: "Production Support", value: "Production Support", recordType: "External" },
		{ title: "Technical call", value: "Technical call", recordType: "External" },
		{ title: "Vacation", value: "Vacation", recordType: "Internal" },
		{ title: "Holiday", value: "Holiday", recordType: "Internal" },
		{ title: "Illness", value: "Illness", recordType: "Internal" },
		{ title: "Group/Company Meeting", value: "Group/Company Meeting", recordType: "Internal" },
		{ title: "Internal Meetings", value: "Internal Meetings", recordType: "Internal" },
		{ title: "Travel", value: "Travel", recordType: "Internal" },
		{ title: "Marketing", value: "Marketing", recordType: "Internal" },
		{ title: "Presales & Sales", value: "Presales & Sales", recordType: "Internal" },
		{ title: "Product Meetings", value: "Product Meetings", recordType: "Internal" },
		{ title: "HR", value: "HR", recordType: "Internal" },
		{ title: "Product Support", value: "Product Support", recordType: "Internal" },
		{ title: "SIK", value: "Strategic Initiatives Work", recordType: "Internal" },
	],
};
